### ISSUE TITLE
POST example?

### ISSUE THREAD

**Issue by ITwrx** [iffy/nim-stripe#1]
Any chance you can add a POST example to the README? Like how to create a Stripe Checkout Session, for instance. 

I'm not clear on how to add the data. 

The data i would need to post would look like this:

```
{
  "success_url": "https://my.app/payment-success",
  "line_items": {
    "0": {
      "price_data": {
        "unit_amount": "995",
        "currency": "usd",
        "product_data": {
          "name": "My App Checkout"
        }
      },
      "quantity": "1"
    }
  },
  "cancel_url": "https://my.app/payment-cancelled",
  "mode": "payment",
  "client_reference_id": "1"
}
```

thanks

**Comment by iffy** [comment]
Thanks for the nudge. I've just update the README with a POST example: https://github.com/iffy/nim-stripe#readme

**Comment by iffy** [comment]
But as I look at it more closely, you want more nesting than the API provides... I'm reopening to consider changing the API to handle that.

**Comment by iffy** [comment]
Oh wait, nevermind. Stripe doesn't accept JSON data, it accepts URL-encoded data, so you'd format your request as:

```nim
client.post("/v1/checkout/sessions", {
  "success_url": "https://my.app/payment-success",
  "line_items[0][price_data][unit_amount]": "995",
  "line_items[0][price_data][currency]": "usd",
  ...
}.toTable()) 
```

**Comment by ITwrx** [comment]
Great, thanks! i'll try it out soon.
